/*
 * This JFrame is responsible for power conversions
 */
package com.CRS.Application;

import com.CRS.Utils.Converter;
import com.CRS.Utils.CoolStuff;

/*
 * Car Registry System / Application / Conversions / Power
 * @author MRX
 * Version : 1.0.0
 */

public class FrmConvertEnginePower extends javax.swing.JFrame {

    /**
     * Creates new form FrmConverterEnginePower
     */
    public FrmConvertEnginePower() {
        initComponents();
        // Custom icon for jar and Jframe
        this.setIconImage(CoolStuff.createIcon().getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpConverter = new javax.swing.ButtonGroup();
        panColor = new javax.swing.JPanel();
        btnConvert = new javax.swing.JButton();
        panHptoKw = new javax.swing.JPanel();
        radHptoKw = new javax.swing.JRadioButton();
        lblHP = new javax.swing.JLabel();
        txtHP = new javax.swing.JTextField();
        lblKW = new javax.swing.JLabel();
        txtKW = new javax.swing.JTextField();
        panKwtoHp = new javax.swing.JPanel();
        radKwtoHp = new javax.swing.JRadioButton();
        lblKW2 = new javax.swing.JLabel();
        txtKW2 = new javax.swing.JTextField();
        lblHP2 = new javax.swing.JLabel();
        txtHP2 = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblTip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRS - Convert Engine Power");
        setResizable(false);

        panColor.setBackground(new java.awt.Color(255, 204, 204));

        btnConvert.setText("Convert");
        btnConvert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConvert.setEnabled(false);
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        panHptoKw.setBackground(new java.awt.Color(255, 204, 204));
        panHptoKw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        grpConverter.add(radHptoKw);
        radHptoKw.setText("hp to kw");
        radHptoKw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radHptoKw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHptoKwActionPerformed(evt);
            }
        });

        lblHP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblHP.setText("hp :");

        txtHP.setEditable(false);
        txtHP.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtHP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHPKeyReleased(evt);
            }
        });

        lblKW.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblKW.setText("kw :");

        txtKW.setEditable(false);
        txtKW.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout panHptoKwLayout = new javax.swing.GroupLayout(panHptoKw);
        panHptoKw.setLayout(panHptoKwLayout);
        panHptoKwLayout.setHorizontalGroup(
            panHptoKwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHptoKwLayout.createSequentialGroup()
                .addGroup(panHptoKwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panHptoKwLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(radHptoKw))
                    .addGroup(panHptoKwLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panHptoKwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKW)
                            .addComponent(txtKW, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHP, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHP))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        panHptoKwLayout.setVerticalGroup(
            panHptoKwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHptoKwLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radHptoKw)
                .addGap(24, 24, 24)
                .addComponent(lblHP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        panKwtoHp.setBackground(new java.awt.Color(255, 204, 204));
        panKwtoHp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        grpConverter.add(radKwtoHp);
        radKwtoHp.setText("kw to hp");
        radKwtoHp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radKwtoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radKwtoHpActionPerformed(evt);
            }
        });

        lblKW2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblKW2.setText("kw :");

        txtKW2.setEditable(false);
        txtKW2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtKW2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKW2KeyReleased(evt);
            }
        });

        lblHP2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblHP2.setText("hp :");

        txtHP2.setEditable(false);
        txtHP2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout panKwtoHpLayout = new javax.swing.GroupLayout(panKwtoHp);
        panKwtoHp.setLayout(panKwtoHpLayout);
        panKwtoHpLayout.setHorizontalGroup(
            panKwtoHpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panKwtoHpLayout.createSequentialGroup()
                .addGroup(panKwtoHpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panKwtoHpLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(radKwtoHp))
                    .addGroup(panKwtoHpLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panKwtoHpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKW2)
                            .addComponent(txtKW2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHP2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHP2))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        panKwtoHpLayout.setVerticalGroup(
            panKwtoHpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panKwtoHpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radKwtoHp)
                .addGap(26, 26, 26)
                .addComponent(lblKW2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKW2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CRS/icons_package/turbo.png"))); // NOI18N
        lblTitle.setText("Engine Power Converter");

        lblTip.setBackground(new java.awt.Color(255, 204, 204));
        lblTip.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTip.setForeground(new java.awt.Color(0, 0, 204));
        lblTip.setText("?");
        lblTip.setToolTipText("horsepower / kilowatt");
        lblTip.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panColorLayout = new javax.swing.GroupLayout(panColor);
        panColor.setLayout(panColorLayout);
        panColorLayout.setHorizontalGroup(
            panColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panColorLayout.createSequentialGroup()
                .addGroup(panColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panColorLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(lblTitle)
                        .addGap(107, 107, 107)
                        .addComponent(lblTip, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panColorLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(panHptoKw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panKwtoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panColorLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(btnConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(656, Short.MAX_VALUE))
        );
        panColorLayout.setVerticalGroup(
            panColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panColorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(lblTip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(panColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panKwtoHp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panHptoKw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConvert)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(530, 367));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed

        // Need to verify which radio was selected
        if(radHptoKw.isSelected()) {

            // We need to parse cc textbox value and pass it to method

            Integer res = Converter.hpToKW(Integer.parseInt(txtHP.getText()));
            txtKW.setText(res.toString());

        } else {

            // We need to parse inch textbox value and pass it to method

            Integer res = Converter.kwToHP(Integer.parseInt(txtKW2.getText()));
            txtHP2.setText(res.toString());

        }

    }//GEN-LAST:event_btnConvertActionPerformed

    private void radHptoKwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHptoKwActionPerformed
        // Enable first panel
        txtHP.setEditable(true);
        txtKW2.setEditable(false);
        txtHP.requestFocus();

        txtHP2.setText(null);
        txtKW2.setText(null);

        btnConvert.setEnabled(true);
    }//GEN-LAST:event_radHptoKwActionPerformed

    private void txtHPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHPKeyReleased
        // Only numbers allowed
        if(! CoolStuff.isNumber(txtHP.getText()))
        txtHP.setText(null);
    }//GEN-LAST:event_txtHPKeyReleased

    private void txtKW2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKW2KeyReleased
        // Only numbers allowed
        if(! CoolStuff.isNumber(txtKW2.getText()))
        txtKW2.setText(null);
    }//GEN-LAST:event_txtKW2KeyReleased

    private void radKwtoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radKwtoHpActionPerformed
        // Enable second panel
        txtKW2.setEditable(true);
        txtHP.setEditable(false);
        txtKW2.requestFocus();

        txtHP.setText(null);
        txtKW.setText(null);

        btnConvert.setEnabled(true);
    }//GEN-LAST:event_radKwtoHpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConvertEnginePower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConvertEnginePower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConvertEnginePower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConvertEnginePower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConvertEnginePower().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvert;
    private javax.swing.ButtonGroup grpConverter;
    private javax.swing.JLabel lblHP;
    private javax.swing.JLabel lblHP2;
    private javax.swing.JLabel lblKW;
    private javax.swing.JLabel lblKW2;
    private javax.swing.JLabel lblTip;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panColor;
    private javax.swing.JPanel panHptoKw;
    private javax.swing.JPanel panKwtoHp;
    private javax.swing.JRadioButton radHptoKw;
    private javax.swing.JRadioButton radKwtoHp;
    private javax.swing.JTextField txtHP;
    private javax.swing.JTextField txtHP2;
    private javax.swing.JTextField txtKW;
    private javax.swing.JTextField txtKW2;
    // End of variables declaration//GEN-END:variables
}
