/*
 * This JFrame is responsible for engine models exclusions
 */
package com.CRS.Application;

import com.CRS.Controller.EngineBusinessLogic;
import com.CRS.Utils.AudioWarning;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * Car Registry System / Application / Engine Model
 * @author MRX
 * Version : 1.0.0
 */

public class FrmDelEngineModel extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmDelEngineModel
     */
    public FrmDelEngineModel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //We need to validate the motive of exclusion
    private boolean validateMotive() { 
        
        if(atxtMotive.getText().isEmpty()) {
            
            //Lets play warning sound with our method
            AudioWarning aw = new AudioWarning();
            aw.errorWarning();
            JOptionPane.showMessageDialog(null, "Inform the motive of this exclusion!"
                                       ,"Delete Error", JOptionPane.ERROR_MESSAGE);
            atxtMotive.requestFocus();
           
            return false;
        }
        return true;
    }
    
    private void setFields() {
        
        int puts = dgvEngineModels.getSelectedRow();
        
        txtEmodel.setText(dgvEngineModels.getModel().getValueAt(puts, 1).toString());
        
        //Let´s activate delete button
        btnDelete.setEnabled(true);
        
    }
    
    private void setDefaultState() {
        
        txtEmodel.setText(null);
        atxtMotive.setText(null);
        btnDelete.setEnabled(false);
        txtModel.setText(null);
        ((DefaultTableModel)dgvEngineModels.getModel()).setRowCount(0);
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panColor = new javax.swing.JPanel();
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        scpPanel = new javax.swing.JScrollPane();
        dgvEngineModels = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        lblMotive = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxtMotive = new javax.swing.JTextArea();
        btnDelete = new javax.swing.JButton();
        lblEmodel = new javax.swing.JLabel();
        txtEmodel = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("CRS - Delete Engine Model");
        setToolTipText("");

        panColor.setBackground(new java.awt.Color(255, 204, 204));

        lblModel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblModel.setText("Engine Model :");

        txtModel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtModel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModelKeyReleased(evt);
            }
        });

        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CRS/icons_package/search.png"))); // NOI18N

        dgvEngineModels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "model", "size", "power", "torque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dgvEngineModels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgvEngineModelsMouseClicked(evt);
            }
        });
        scpPanel.setViewportView(dgvEngineModels);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 0, 51));
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CRS/icons_package/engine.png"))); // NOI18N
        lblTitle.setText("Delete* Engine");

        lblMotive.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMotive.setText("Motive * :");

        atxtMotive.setColumns(20);
        atxtMotive.setRows(5);
        jScrollPane1.setViewportView(atxtMotive);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CRS/images/x-button.png"))); // NOI18N
        btnDelete.setToolTipText("Delete engine model");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblEmodel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmodel.setText("Model :");

        txtEmodel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmodel.setEnabled(false);

        javax.swing.GroupLayout panColorLayout = new javax.swing.GroupLayout(panColor);
        panColor.setLayout(panColorLayout);
        panColorLayout.setHorizontalGroup(
            panColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panColorLayout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addGroup(panColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panColorLayout.createSequentialGroup()
                                .addComponent(lblTitle)
                                .addGap(387, 387, 387))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panColorLayout.createSequentialGroup()
                                .addComponent(lblMotive, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(614, 614, 614)))
                        .addGroup(panColorLayout.createSequentialGroup()
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblSearch))
                        .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(scpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panColorLayout.createSequentialGroup()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(443, 443, 443))))
        );
        panColorLayout.setVerticalGroup(
            panColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panColorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(47, 47, 47)
                .addComponent(lblModel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmodel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblMotive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1000, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void txtModelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModelKeyReleased
        EngineBusinessLogic engine = new EngineBusinessLogic();
        dgvEngineModels.setModel(DbUtils.resultSetToTableModel
            (engine.searchEnginesModels(txtModel.getText())));
        /*
        * searchEnginesModels method returns a ResultSet and DbUtil
        * insert this ResultSet into a jTable
        */
    }//GEN-LAST:event_txtModelKeyReleased

    private void dgvEngineModelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgvEngineModelsMouseClicked
        // Set all fields with JTabel selected row contents
        this.setFields();
    }//GEN-LAST:event_dgvEngineModelsMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Delete engine
        if(this.validateMotive()) {
           
            EngineBusinessLogic engine = new EngineBusinessLogic();
            engine.deleteEngineModel(txtEmodel.getText(), FrmHome.lblUserName.getText(),
                                                                  atxtMotive.getText());
            this.setDefaultState();
            
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxtMotive;
    private javax.swing.JButton btnDelete;
    private javax.swing.JTable dgvEngineModels;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmodel;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblMotive;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panColor;
    private javax.swing.JScrollPane scpPanel;
    private javax.swing.JTextField txtEmodel;
    private javax.swing.JTextField txtModel;
    // End of variables declaration//GEN-END:variables
}
